### PR TITLE
add VCRSystem option to force-deactivate recording and only do playback

### PR DESCRIPTION
**Pull request by megies**
I want to add the possibility to force vcr to only do playback and no recording. This should be the default for `obspy-runtests` to ensure that no networking is done during test runs. Otherwise when a tape is missing VCR would automatically switch to recording and test runs that miss a tape might silently pass although they should fail due to the missing tape.

When a tape is missing this will show up as follows:

```
$ obspy-runtests clients.fdsn
Running /home/megies/git/obspy-master/obspy/scripts/runtests.py, ObsPy version '1.0.3.post0+1007.g3e632f463b.dirty.obspy.vcr'
.................E...........E..ss.................................................................

======================================================================
ERROR: test_dataselect_bulk (obspy.clients.fdsn.tests.test_client.ClientTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<decorator-gen-62>", line 2, in test_dataselect_bulk
  File "/home/megies/git/obspy-master/obspy/core/util/decorator.py", line 86, in vcr
    vcr_module.vcr(decorated_func=func)(*args, **kwargs)
  File "/home/megies/git/vcr/vcr/core.py", line 505, in _vcr_inner
    raise Exception(msg)
Exception: Missing VCR tape file for playback: /home/megies/git/obspy-master/obspy/clients/fdsn/tests/vcrtapes/test_client.test_dataselect_bulk.vcr

======================================================================
ERROR: test_manually_deactivate_single_service (obspy.clients.fdsn.tests.test_client.ClientTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<decorator-gen-65>", line 2, in test_manually_deactivate_single_service
  File "/home/megies/git/obspy-master/obspy/core/util/decorator.py", line 86, in vcr
    vcr_module.vcr(decorated_func=func)(*args, **kwargs)
  File "/home/megies/git/vcr/vcr/core.py", line 505, in _vcr_inner
    raise Exception(msg)
Exception: Missing VCR tape file for playback: /home/megies/git/obspy-master/obspy/clients/fdsn/tests/vcrtapes/test_client.test_manually_deactivate_single_service.vcr

----------------------------------------------------------------------
Ran 99 tests in 2.437s

FAILED (errors=2)
Do you want to report this to tests.obspy.org? [n]: 
```

Any complaints about this new option @barsch?

### CODE REVIEW

**Review by barsch — APPROVED** [review]
fine with me - currently only as global option implemented

**Comment by megies** [comment]
Thanks for feedback. And yeah, didn't bother to add it to the decorator as well, one big global switch is enough I think.

**Comment by barsch** [comment]
I'll add on local level too and test and docs ;)

**Comment by megies** [comment]
Ooops, sorry.. too fast, pushed 0.0.7, so you'll have to increment version again when you're done..

**Comment by barsch** [comment]
i will - no worries

**Pull request merged**
